// Code generated by protoc-gen-zig
///! package google.protobuf
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const FileDescriptorSet = struct {
    file: ArrayList(FileDescriptorProto),

    pub const _desc_table = .{
        .file = fd(1, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FileDescriptorProto = struct {
    name: ?ManagedString = null,
    package: ?ManagedString = null,
    dependency: ArrayList(ManagedString),
    public_dependency: ArrayList(i32),
    weak_dependency: ArrayList(i32),
    message_type: ArrayList(DescriptorProto),
    enum_type: ArrayList(EnumDescriptorProto),
    service: ArrayList(ServiceDescriptorProto),
    extension: ArrayList(FieldDescriptorProto),
    options: ?FileOptions = null,
    source_code_info: ?SourceCodeInfo = null,
    syntax: ?ManagedString = null,
    edition: ?ManagedString = null,

    pub const _desc_table = .{
        .name = fd(1, null, .String),
        .package = fd(2, null, .String),
        .dependency = fd(3, null, .{ .List = .String }),
        .public_dependency = fd(10, null, .{ .List = .{ .Varint = .Simple } }),
        .weak_dependency = fd(11, null, .{ .List = .{ .Varint = .Simple } }),
        .message_type = fd(4, null, .{ .List = .{ .SubMessage = {} } }),
        .enum_type = fd(5, null, .{ .List = .{ .SubMessage = {} } }),
        .service = fd(6, null, .{ .List = .{ .SubMessage = {} } }),
        .extension = fd(7, null, .{ .List = .{ .SubMessage = {} } }),
        .options = fd(8, null, .{ .SubMessage = {} }),
        .source_code_info = fd(9, null, .{ .SubMessage = {} }),
        .syntax = fd(12, null, .String),
        .edition = fd(13, null, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DescriptorProto = struct {
    name: ?ManagedString = null,
    field: ArrayList(FieldDescriptorProto),
    extension: ArrayList(FieldDescriptorProto),
    nested_type: ArrayList(DescriptorProto),
    enum_type: ArrayList(EnumDescriptorProto),
    extension_range: ArrayList(ExtensionRange),
    oneof_decl: ArrayList(OneofDescriptorProto),
    options: ?MessageOptions = null,
    reserved_range: ArrayList(ReservedRange),
    reserved_name: ArrayList(ManagedString),

    pub const _desc_table = .{
        .name = fd(1, null, .String),
        .field = fd(2, null, .{ .List = .{ .SubMessage = {} } }),
        .extension = fd(6, null, .{ .List = .{ .SubMessage = {} } }),
        .nested_type = fd(3, null, .{ .List = .{ .SubMessage = {} } }),
        .enum_type = fd(4, null, .{ .List = .{ .SubMessage = {} } }),
        .extension_range = fd(5, null, .{ .List = .{ .SubMessage = {} } }),
        .oneof_decl = fd(8, null, .{ .List = .{ .SubMessage = {} } }),
        .options = fd(7, null, .{ .SubMessage = {} }),
        .reserved_range = fd(9, null, .{ .List = .{ .SubMessage = {} } }),
        .reserved_name = fd(10, null, .{ .List = .String }),
    };

    pub const ExtensionRange = struct {
        start: ?i32 = null,
        end: ?i32 = null,
        options: ?ExtensionRangeOptions = null,

        pub const _desc_table = .{
            .start = fd(1, null, .{ .Varint = .Simple }),
            .end = fd(2, null, .{ .Varint = .Simple }),
            .options = fd(3, null, .{ .SubMessage = {} }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const ReservedRange = struct {
        start: ?i32 = null,
        end: ?i32 = null,

        pub const _desc_table = .{
            .start = fd(1, null, .{ .Varint = .Simple }),
            .end = fd(2, null, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ExtensionRangeOptions = struct {
    uninterpreted_option: ArrayList(UninterpretedOption),
    declaration: ArrayList(Declaration),
    verification: ?VerificationState = .UNVERIFIED,

    pub const _desc_table = .{
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
        .declaration = fd(2, null, .{ .List = .{ .SubMessage = {} } }),
        .verification = fd(3, null, .{ .Varint = .Simple }),
    };

    pub const VerificationState = enum(i32) {
        DECLARATION = 0,
        UNVERIFIED = 1,
        _,
    };

    pub const Declaration = struct {
        number: ?i32 = null,
        full_name: ?ManagedString = null,
        type: ?ManagedString = null,
        is_repeated: ?bool = null,
        reserved: ?bool = null,
        repeated: ?bool = null,

        pub const _desc_table = .{
            .number = fd(1, null, .{ .Varint = .Simple }),
            .full_name = fd(2, null, .String),
            .type = fd(3, null, .String),
            .is_repeated = fd(4, null, .{ .Varint = .Simple }),
            .reserved = fd(5, null, .{ .Varint = .Simple }),
            .repeated = fd(6, null, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FieldDescriptorProto = struct {
    name: ?ManagedString = null,
    number: ?i32 = null,
    label: ?Label = null,
    type: ?Type = null,
    type_name: ?ManagedString = null,
    extendee: ?ManagedString = null,
    default_value: ?ManagedString = null,
    oneof_index: ?i32 = null,
    json_name: ?ManagedString = null,
    options: ?FieldOptions = null,
    proto3_optional: ?bool = null,

    pub const _desc_table = .{
        .name = fd(1, null, .String),
        .number = fd(3, null, .{ .Varint = .Simple }),
        .label = fd(4, null, .{ .Varint = .Simple }),
        .type = fd(5, null, .{ .Varint = .Simple }),
        .type_name = fd(6, null, .String),
        .extendee = fd(2, null, .String),
        .default_value = fd(7, null, .String),
        .oneof_index = fd(9, null, .{ .Varint = .Simple }),
        .json_name = fd(10, null, .String),
        .options = fd(8, null, .{ .SubMessage = {} }),
        .proto3_optional = fd(17, null, .{ .Varint = .Simple }),
    };

    pub const Type = enum(i32) {
        TYPE_DOUBLE = 1,
        TYPE_FLOAT = 2,
        TYPE_INT64 = 3,
        TYPE_UINT64 = 4,
        TYPE_INT32 = 5,
        TYPE_FIXED64 = 6,
        TYPE_FIXED32 = 7,
        TYPE_BOOL = 8,
        TYPE_STRING = 9,
        TYPE_GROUP = 10,
        TYPE_MESSAGE = 11,
        TYPE_BYTES = 12,
        TYPE_UINT32 = 13,
        TYPE_ENUM = 14,
        TYPE_SFIXED32 = 15,
        TYPE_SFIXED64 = 16,
        TYPE_SINT32 = 17,
        TYPE_SINT64 = 18,
        _,
    };

    pub const Label = enum(i32) {
        LABEL_OPTIONAL = 1,
        LABEL_REQUIRED = 2,
        LABEL_REPEATED = 3,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OneofDescriptorProto = struct {
    name: ?ManagedString = null,
    options: ?OneofOptions = null,

    pub const _desc_table = .{
        .name = fd(1, null, .String),
        .options = fd(2, null, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EnumDescriptorProto = struct {
    name: ?ManagedString = null,
    value: ArrayList(EnumValueDescriptorProto),
    options: ?EnumOptions = null,
    reserved_range: ArrayList(EnumReservedRange),
    reserved_name: ArrayList(ManagedString),

    pub const _desc_table = .{
        .name = fd(1, null, .String),
        .value = fd(2, null, .{ .List = .{ .SubMessage = {} } }),
        .options = fd(3, null, .{ .SubMessage = {} }),
        .reserved_range = fd(4, null, .{ .List = .{ .SubMessage = {} } }),
        .reserved_name = fd(5, null, .{ .List = .String }),
    };

    pub const EnumReservedRange = struct {
        start: ?i32 = null,
        end: ?i32 = null,

        pub const _desc_table = .{
            .start = fd(1, null, .{ .Varint = .Simple }),
            .end = fd(2, null, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EnumValueDescriptorProto = struct {
    name: ?ManagedString = null,
    number: ?i32 = null,
    options: ?EnumValueOptions = null,

    pub const _desc_table = .{
        .name = fd(1, null, .String),
        .number = fd(2, null, .{ .Varint = .Simple }),
        .options = fd(3, null, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ServiceDescriptorProto = struct {
    name: ?ManagedString = null,
    method: ArrayList(MethodDescriptorProto),
    options: ?ServiceOptions = null,

    pub const _desc_table = .{
        .name = fd(1, null, .String),
        .method = fd(2, null, .{ .List = .{ .SubMessage = {} } }),
        .options = fd(3, null, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MethodDescriptorProto = struct {
    name: ?ManagedString = null,
    input_type: ?ManagedString = null,
    output_type: ?ManagedString = null,
    options: ?MethodOptions = null,
    client_streaming: ?bool = false,
    server_streaming: ?bool = false,

    pub const _desc_table = .{
        .name = fd(1, null, .String),
        .input_type = fd(2, null, .String),
        .output_type = fd(3, null, .String),
        .options = fd(4, null, .{ .SubMessage = {} }),
        .client_streaming = fd(5, null, .{ .Varint = .Simple }),
        .server_streaming = fd(6, null, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FileOptions = struct {
    java_package: ?ManagedString = null,
    java_outer_classname: ?ManagedString = null,
    java_multiple_files: ?bool = false,
    java_generate_equals_and_hash: ?bool = null,
    java_string_check_utf8: ?bool = false,
    optimize_for: ?OptimizeMode = .SPEED,
    go_package: ?ManagedString = null,
    cc_generic_services: ?bool = false,
    java_generic_services: ?bool = false,
    py_generic_services: ?bool = false,
    php_generic_services: ?bool = false,
    deprecated: ?bool = false,
    cc_enable_arenas: ?bool = true,
    objc_class_prefix: ?ManagedString = null,
    csharp_namespace: ?ManagedString = null,
    swift_prefix: ?ManagedString = null,
    php_class_prefix: ?ManagedString = null,
    php_namespace: ?ManagedString = null,
    php_metadata_namespace: ?ManagedString = null,
    ruby_package: ?ManagedString = null,
    uninterpreted_option: ArrayList(UninterpretedOption),

    pub const _desc_table = .{
        .java_package = fd(1, null, .String),
        .java_outer_classname = fd(8, null, .String),
        .java_multiple_files = fd(10, null, .{ .Varint = .Simple }),
        .java_generate_equals_and_hash = fd(20, null, .{ .Varint = .Simple }),
        .java_string_check_utf8 = fd(27, null, .{ .Varint = .Simple }),
        .optimize_for = fd(9, null, .{ .Varint = .Simple }),
        .go_package = fd(11, null, .String),
        .cc_generic_services = fd(16, null, .{ .Varint = .Simple }),
        .java_generic_services = fd(17, null, .{ .Varint = .Simple }),
        .py_generic_services = fd(18, null, .{ .Varint = .Simple }),
        .php_generic_services = fd(42, null, .{ .Varint = .Simple }),
        .deprecated = fd(23, null, .{ .Varint = .Simple }),
        .cc_enable_arenas = fd(31, null, .{ .Varint = .Simple }),
        .objc_class_prefix = fd(36, null, .String),
        .csharp_namespace = fd(37, null, .String),
        .swift_prefix = fd(39, null, .String),
        .php_class_prefix = fd(40, null, .String),
        .php_namespace = fd(41, null, .String),
        .php_metadata_namespace = fd(44, null, .String),
        .ruby_package = fd(45, null, .String),
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const OptimizeMode = enum(i32) {
        SPEED = 1,
        CODE_SIZE = 2,
        LITE_RUNTIME = 3,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MessageOptions = struct {
    message_set_wire_format: ?bool = false,
    no_standard_descriptor_accessor: ?bool = false,
    deprecated: ?bool = false,
    map_entry: ?bool = null,
    deprecated_legacy_json_field_conflicts: ?bool = null,
    uninterpreted_option: ArrayList(UninterpretedOption),
    cmd_id: ?u16,

    pub const _desc_table = .{
        .message_set_wire_format = fd(1, null, .{ .Varint = .Simple }),
        .no_standard_descriptor_accessor = fd(2, null, .{ .Varint = .Simple }),
        .deprecated = fd(3, null, .{ .Varint = .Simple }),
        .map_entry = fd(7, null, .{ .Varint = .Simple }),
        .deprecated_legacy_json_field_conflicts = fd(11, null, .{ .Varint = .Simple }),
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
        .cmd_id = fd(1001, null, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FieldOptions = struct {
    ctype: ?CType = .STRING,
    @"packed": ?bool = null,
    jstype: ?JSType = .JS_NORMAL,
    lazy: ?bool = false,
    unverified_lazy: ?bool = false,
    deprecated: ?bool = false,
    weak: ?bool = false,
    debug_redact: ?bool = false,
    retention: ?OptionRetention = null,
    target: ?OptionTargetType = null,
    targets: ArrayList(OptionTargetType),
    uninterpreted_option: ArrayList(UninterpretedOption),
    xor: ?u32 = null,

    pub const _desc_table = .{
        .ctype = fd(1, null, .{ .Varint = .Simple }),
        .@"packed" = fd(2, null, .{ .Varint = .Simple }),
        .jstype = fd(6, null, .{ .Varint = .Simple }),
        .lazy = fd(5, null, .{ .Varint = .Simple }),
        .unverified_lazy = fd(15, null, .{ .Varint = .Simple }),
        .deprecated = fd(3, null, .{ .Varint = .Simple }),
        .weak = fd(10, null, .{ .Varint = .Simple }),
        .debug_redact = fd(16, null, .{ .Varint = .Simple }),
        .retention = fd(17, null, .{ .Varint = .Simple }),
        .target = fd(18, null, .{ .Varint = .Simple }),
        .targets = fd(19, null, .{ .List = .{ .Varint = .Simple } }),
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
        .xor = fd(1001, null, .{ .Varint = .Simple }),
    };

    pub const CType = enum(i32) {
        STRING = 0,
        CORD = 1,
        STRING_PIECE = 2,
        _,
    };

    pub const JSType = enum(i32) {
        JS_NORMAL = 0,
        JS_STRING = 1,
        JS_NUMBER = 2,
        _,
    };

    pub const OptionRetention = enum(i32) {
        RETENTION_UNKNOWN = 0,
        RETENTION_RUNTIME = 1,
        RETENTION_SOURCE = 2,
        _,
    };

    pub const OptionTargetType = enum(i32) {
        TARGET_TYPE_UNKNOWN = 0,
        TARGET_TYPE_FILE = 1,
        TARGET_TYPE_EXTENSION_RANGE = 2,
        TARGET_TYPE_MESSAGE = 3,
        TARGET_TYPE_FIELD = 4,
        TARGET_TYPE_ONEOF = 5,
        TARGET_TYPE_ENUM = 6,
        TARGET_TYPE_ENUM_ENTRY = 7,
        TARGET_TYPE_SERVICE = 8,
        TARGET_TYPE_METHOD = 9,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OneofOptions = struct {
    uninterpreted_option: ArrayList(UninterpretedOption),

    pub const _desc_table = .{
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EnumOptions = struct {
    allow_alias: ?bool = null,
    deprecated: ?bool = false,
    deprecated_legacy_json_field_conflicts: ?bool = null,
    uninterpreted_option: ArrayList(UninterpretedOption),

    pub const _desc_table = .{
        .allow_alias = fd(2, null, .{ .Varint = .Simple }),
        .deprecated = fd(3, null, .{ .Varint = .Simple }),
        .deprecated_legacy_json_field_conflicts = fd(6, null, .{ .Varint = .Simple }),
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EnumValueOptions = struct {
    deprecated: ?bool = false,
    uninterpreted_option: ArrayList(UninterpretedOption),

    pub const _desc_table = .{
        .deprecated = fd(1, null, .{ .Varint = .Simple }),
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ServiceOptions = struct {
    deprecated: ?bool = false,
    uninterpreted_option: ArrayList(UninterpretedOption),

    pub const _desc_table = .{
        .deprecated = fd(33, null, .{ .Varint = .Simple }),
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MethodOptions = struct {
    deprecated: ?bool = false,
    idempotency_level: ?IdempotencyLevel = .IDEMPOTENCY_UNKNOWN,
    uninterpreted_option: ArrayList(UninterpretedOption),

    pub const _desc_table = .{
        .deprecated = fd(33, null, .{ .Varint = .Simple }),
        .idempotency_level = fd(34, null, .{ .Varint = .Simple }),
        .uninterpreted_option = fd(999, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const IdempotencyLevel = enum(i32) {
        IDEMPOTENCY_UNKNOWN = 0,
        NO_SIDE_EFFECTS = 1,
        IDEMPOTENT = 2,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const UninterpretedOption = struct {
    name: ArrayList(NamePart),
    identifier_value: ?ManagedString = null,
    positive_int_value: ?u64 = null,
    negative_int_value: ?i64 = null,
    double_value: ?f64 = null,
    string_value: ?ManagedString = null,
    aggregate_value: ?ManagedString = null,

    pub const _desc_table = .{
        .name = fd(2, null, .{ .List = .{ .SubMessage = {} } }),
        .identifier_value = fd(3, null, .String),
        .positive_int_value = fd(4, null, .{ .Varint = .Simple }),
        .negative_int_value = fd(5, null, .{ .Varint = .Simple }),
        .double_value = fd(6, null, .{ .FixedInt = .I64 }),
        .string_value = fd(7, null, .String),
        .aggregate_value = fd(8, null, .String),
    };

    pub const NamePart = struct {
        name_part: ManagedString,
        is_extension: bool,

        pub const _desc_table = .{
            .name_part = fd(1, null, .String),
            .is_extension = fd(2, null, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const SourceCodeInfo = struct {
    location: ArrayList(Location),

    pub const _desc_table = .{
        .location = fd(1, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const Location = struct {
        path: ArrayList(i32),
        span: ArrayList(i32),
        leading_comments: ?ManagedString = null,
        trailing_comments: ?ManagedString = null,
        leading_detached_comments: ArrayList(ManagedString),

        pub const _desc_table = .{
            .path = fd(1, null, .{ .PackedList = .{ .Varint = .Simple } }),
            .span = fd(2, null, .{ .PackedList = .{ .Varint = .Simple } }),
            .leading_comments = fd(3, null, .String),
            .trailing_comments = fd(4, null, .String),
            .leading_detached_comments = fd(6, null, .{ .List = .String }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GeneratedCodeInfo = struct {
    annotation: ArrayList(Annotation),

    pub const _desc_table = .{
        .annotation = fd(1, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const Annotation = struct {
        path: ArrayList(i32),
        source_file: ?ManagedString = null,
        begin: ?i32 = null,
        end: ?i32 = null,
        semantic: ?Semantic = null,

        pub const _desc_table = .{
            .path = fd(1, null, .{ .PackedList = .{ .Varint = .Simple } }),
            .source_file = fd(2, null, .String),
            .begin = fd(3, null, .{ .Varint = .Simple }),
            .end = fd(4, null, .{ .Varint = .Simple }),
            .semantic = fd(5, null, .{ .Varint = .Simple }),
        };

        pub const Semantic = enum(i32) {
            NONE = 0,
            SET = 1,
            ALIAS = 2,
            _,
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
