// Code generated by protoc-gen-zig
///! package head
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const PacketHead = struct {
    pub const CmdId = 0;
    packet_id: u32 = 0,
    ack_packet_id: u32 = 0,

    pub const _desc_table = .{
        .packet_id = fd(1, null, .{ .Varint = .Simple }),
        .ack_packet_id = fd(11, null, .{ .Varint = .Simple }),
    };
    pub fn getCmdId(_: *const @This()) u16 {
        return @This().CmdId;
    }

    pub usingnamespace protobuf.MessageMixins(@This());
};
