// Code generated by protoc-gen-zig
///! package nap_action
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const ActionOpenUi = struct {
    pub const CmdId = 0;
    ui: ManagedString = .Empty,
    args: i32 = 0,
    store_template_id: i32 = 0,
    npc_id: i32 = 0,

    pub const _desc_table = .{
        .ui = fd(1, null, .String),
        .args = fd(2, null, .{ .Varint = .Simple }),
        .store_template_id = fd(4, null, .{ .Varint = .Simple }),
        .npc_id = fd(5, null, .{ .Varint = .Simple }),
    };
    pub fn getCmdId(_: *const @This()) u16 {
        return @This().CmdId;
    }

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ActionSwitchSection = struct {
    pub const CmdId = 0;
    section_id: u32 = 0,
    transform_id: ManagedString = .Empty,
    camera_x: u32 = 0,
    camera_y: u32 = 0,

    pub const _desc_table = .{
        .section_id = fd(1, null, .{ .Varint = .Simple }),
        .transform_id = fd(2, null, .String),
        .camera_x = fd(3, null, .{ .Varint = .Simple }),
        .camera_y = fd(4, null, .{ .Varint = .Simple }),
    };
    pub fn getCmdId(_: *const @This()) u16 {
        return @This().CmdId;
    }

    pub usingnamespace protobuf.MessageMixins(@This());
};
